config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :bands
resources :events
resources :venues

get '/bands' => 'bands#index'
get '/bands:id' => 'bands#show'
get '/venues' => 'venues#index'
get '/venues/:id' => 'venues#show'
get '/events' => 'events#index'
get '/events/:id' => 'events#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
	has_many :events 
	has_many :venues, :through => :events 
	validates :name, presence: true, uniqueness: true
	validates :genre, presence: true
end

app/models/event.rb
class Event < ApplicationRecord 
	belongs_to :band
	belongs_to :venue
	validates :date, presence: true 
end

app/models/venue.rb
class Venue < ApplicationRecord
	has_many :bands, :through => :events
	has_many :events 
	validates :name, presence: true
	validates :city, presence: true
	validates :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

	def index 
		@bands = Band.all
	end

	def new 
		@band = Band.new
	end 

	def create 
		@band = Band.create(name: params[:band][:name],genre: params[:band][:genre],explicit_lyrics: params[:band][:explicit_lyrics])
		redirect_to bands_path
	end

	def edit 
		@band = Band.find(params[:id])
	end 

	def destroy
		@band = Band.find(params[:id])
		@band.destroy
		redirect_to bands_path
	end

	def update
		@band = Band.find(params[:id])
		@band.update(name: params[:band][:name], genre: params[:band][:genre], explicit_lyrics: params[:band][:explicit_lyrics])
		redirect_to bands_path
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index 
		@events = Event.all 
	end 

	def new 
		@event = Event.new 
	end 

	def create 
		@event = Event.create(date: params[:event][:date],alcohol_served: params[:event][:alcohol_served])
		redirect_to events_path 
	end 

	def edit 
		@event = Event.find(params[:id])
	end 

	def show 
		@event = Event.find(params[:id])
	end 

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end

	def update
		@event = Event.find(params[:id])
		@event.update(date: params[:event][:date], alcohol_served: params[:event][:alcohol_served])
		redirect_to events_path
	end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

	def index 
		@venues = Venue.all
	end

	def new 
		@venue = Venue.new
	end

	def create 
		@venue = Venue.create(name: params[:venue][:name],city: params[:venue][:city], state: params[:venue][:state], family_friendly: params[:venue][:family_friendly])	
		redirect_to venues_path
	end

	def edit 
		@venue = Venue.find(params[:id])
	end

	def show 
		@venue = Venue.find(params[:id])
	end

	def destroy
		@venue = Venue.find(params[:id])
		@venue.destroy
		redirect_to venues_path
	end

	def update
		@venue = Venue.find(params[:id])
		@venue.update(name: params[:venue][:name], city: params[:venue][:city], state: params[:venue][:state], family_friendly: params[:venue][:family_friendly])
		redirect_to venues_path
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/venue_helper.rb
module VenueHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/bands/edit.html.erb
<%= bootstrap_form_for(@band, layout: :horizontal) do |t| %>
			<p><%= t.text_field :name %></p>
			<p><%= t.text_field :genre %></p>
			<p><%= t.text_field :explicit_lyrics %></p>
			
		<div class="text-center">
				<%= submit_tag "Confirm" %>
		</div>
		<% end %>

app/views/bands/index.html.erb
<h1>Band</h1>

<% @bands.each do |t| %>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Genre</th>
            <th>Explicit Lyrics</th>
        </tr>
    </thead>
    <tbody>
<tr>
<td><%= t.name %></td>
<td><%= t.genre %></td>
<td><%= t.explicit_lyrics %></td>
<td><%= link_to "Edit Band", edit_band_path(t) %></td>
<td><%= link_to "Delete Band", band_path(t), method: :delete, data: {confirm: "Are you sure?"} %><td>
</tr>
<% end %>
</tbody>
</table>

<div class="container">
  <div class="text-center">
<p> <%= link_to "Add a new Band", new_band_path %> </p>
</div>
</div>

app/views/bands/new.html.erb
<div class="container">
	<div class="text-center">
		<h1>Add New Band</h1>
	</div>
		<div class="text-center">

			<%= bootstrap_form_for(@band, layout: :vertical) do |f|%>
				<label><%= f.text_field :name %></label>
				<label><%= f.text_field :genre %></label>
				<label><%= f.text_field :explicit_lyrics %></label>
		<div class="text-center">
			<%= submit_tag "Add" %>
		</div>
		<% end %>
	</div>
</div>

app/views/events/edit.html.erb
<%= bootstrap_form_for(@event, layout: :horizontal) do |t| %>
			<p><%= t.text_field :date %></p>
			<p><%= t.text_field :alcohol_served %></p>
		<div class="text-center">
				<%= submit_tag "Confirm" %>
		</div>
		<% end %>

app/views/events/index.html.erb
<h1>Event</h1>

<% @events.each do |t| %>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Date</th>
            <th>Alcohol Served</th>
        </tr>
    </thead>
    <tbody>
<tr>
<td><%= t.date %></td>
<td><%= t.alcohol_served %></td>
<td><%= link_to "Edit Event", edit_event_path(t) %></td>
<td><%= link_to "Delete Event", event_path(t), method: :delete, data: {confirm: "Are you sure?"} %><td>
</tr>
<% end %>
</tbody>
</table>

<div class="container">
  <div class="text-center">
<p> <%= link_to "Add a new Event", new_event_path %> </p>
</div>
</div>

app/views/events/new.html.erb
<div class="container">
	<div class="text-center">
		<h1>Add New Event</h1>
	</div>
		<div class="text-center">

			<%= bootstrap_form_for(@event, layout: :vertical) do |f|%>
				<label><%= f.text_field :date %></label>
				<label><%= f.text_field :alcohol_served %></label>				
		<div class="text-center">
			<%= submit_tag "Add" %>
		</div>
		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<p>
	<%= @event.content %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BandApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   
  </head>

  <body>

 
    <%= image_tag("band/ny.png") %>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">Band.io</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a <%= link_to "Band", bands_path %> </a></li>
        <li><a <%= link_to "Venue", venues_path %> </a></li>
        <li><a <%= link_to "Event", events_path %></a></li>
      </ul>
    </div>
  </div>
</nav>



    <%= yield %>

  </body>
</html>

app/views/venues/edit.html.erb
<%= bootstrap_form_for(@venue, layout: :horizontal) do |t| %>
			<p><%= t.text_field :name %></p>
			<p><%= t.text_field :city %></p>
			<p><%= t.text_field :state %></p>
			<p><%= t.text_field :family_friendly %></p>
			
		<div class="text-center">
				<%= submit_tag "Confirm" %>
		</div>
		<% end %>

app/views/venues/index.html.erb
<h1>Venue</h1>

<% @venues.each do |t| %>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>City</th>
            <th>State</th>
            <th>Family Friendly</th>
        </tr>
    </thead>
    <tbody>
<tr>
<td><%= t.name %></td>
<td><%= t.city %></td>
<td><%= t.state %></td>
<td><%= t.family_friendly %></td>
<td><%= link_to "Edit Venue", edit_venue_path(t) %></td>
<td><%= link_to "Delete Venue", venue_path(t), method: :delete, data: {confirm: "Are you sure?"} %><td>
</tr>
<% end %>
</tbody>
</table>

<div class="container">
  <div class="text-center">
<p> <%= link_to "Add a new Venue", new_venue_path %> </p>
</div>
</div>

app/views/venues/new.html.erb
<div class="container">
	<div class="text-center">
		<h1>Add New Venue</h1>
	</div>
		<div class="text-center">

			<%= bootstrap_form_for(@venue, layout: :vertical) do |f|%>
				<label><%= f.text_field :name %></label>
				<label><%= f.text_field :city %></label>
				<label><%= f.text_field :state %></label>
				<label><%= f.text_field :family_friendly %></label>
		<div class="text-center">
			<%= submit_tag "Add" %>
		</div>
		<% end %>
	</div>
</div>

app/views/venues/show.html.erb
<h1><%= @venue.title %></h1>

<p>
	<%= @venue.content %>
</p>